### ISSUE TITLE
RestfulServer::getMember() returns null even when logged in

### ISSUE THREAD

**Issue by lukereative** [silverstripe/silverstripe-restfulserver#52] opened 2018-03-07 02:02 UTC
Steps to reproduce:

1. Hit `api/v1/Page` where page has `$api_access = true`
2. Debug `RestfulServer::getMember` -> returns null
3. Log into the CMS
4. Hit the api again
5. `getMember` still returns null

**Comment by dhensby** [comment] 2018-03-07 11:49
Restful services don't run on sessions or cookie based authentication - so logging into the CMS shouldn't make any difference.

How are you authenticating against the RestfulServer? Have you set up your own authentication class or using the default one?

**Comment by robbieaverill** [comment] 2018-04-04 03:34
Closing as it seems this is expected behaviour

**Closed by robbieaverill** 2018-04-04 03:34 UTC
Labels: affects/v4, change/patch, effort/medium, impact/medium, type/bug

**Comment by phptek** [comment] 2019-06-03 18:45
Hmmm, I'd like to see this re-opened.

If a user is authenticated.
That user should be able to see the content they're entitled to see.
Period.

If specific things need to be hidden / filtered, this can be done use `canView()` and `$api_access`.

For the moment, this functionality makes no sense to me. Looking at the logic in `RestfulServer::index()` I see the following:

```php
$this->member = $this->authenticate()
```

There is no check to see if the current request comes from an authenticated user. The logic hard-out assumes the request cannot possibly be coming from an authenticated source, and goes ahead and runs us through its own `Authenticator` implementation.

ATM, I have subclassed `RestfulServer` and overload `authenticate()` to simply return `Security::getCurrentUser()`. Which works 100% for my situation.

I would of course be very happy for someone to explain why what I'm doing is a bad idea. But if it isn't, or someone can't, then I'd suggest these are grounds for re-looking at the default auth logic here.

**Comment by phptek** [comment] 2019-06-03 19:04
@dhensby 
> Restful services don't run on sessions or cookie based authentication

By "Restful services" do you mean this module, or "REST" services in general? Can you point us to a resource that suggests we shouldn't be using cookie/session based auth for REST services? Cheers :-)

**Comment by robbieaverill** [comment] 2019-06-03 21:11
For reference, GraphQL allows session based authentication, but it loads the member and uses it as an argument for canView() etc calls rather than actually performing a login on that member. The same (in GraphQL) for basic authentication - it returns the member you're authenticating as rather than logging you in as it. In this way, API requests are stateless because you're always providing the member to authenticate as rather than relying on it being in the session.

I think that if you want to change this behaviour then it should be done in custom code. Do you agree?

**Comment by phptek** [comment] 2019-06-03 21:36
Maybe. Right now I feel like the module is making assumptions about how developers want to access their data and by default, pointing them down a specific path. We don't request users to login my default when accessing other view-based data in the front-end e.g standard page content.

By all means offer an authentication hook, but don't assume and enforce authentication as a default.

Thoughts welcome.

**Comment by ScopeyNZ** [comment] 2019-06-03 23:22
I think what we have is valid. It's more common for APIs to NOT use session authentication - for good reason in some cases where you might have a server running API request for multiple users.

You could have a "nicer" way of doing the auth instead of overloading `RestfulServer::authenticate`. You could create your own `RestfulAuthenticator` (eg. `SessionAuthenticator`) which just returns the current user:

```
namespace My\Project\RestfulServer;

class SessionAuthenticator
{
    public static function authenticate()
    {
        return Security::getCurrentUser();
    }
}
```

And then you can use this with configuration:

```
SilverStripe\RestfulServer\RestfulServer:
  authenticator: 'My\Project\RestfulServer\SessionAuthenticator'
```

I would welcome a PR that adds this authenticator and docs updates to accompany this - but I strongly disagree with changing the default authenticator.

I also think this API could really be improved. Authenticators in this module really should be interfaced - and they should probably have easy access to the request they're trying to authenticate 😅

**Comment by dhensby** [comment] 2019-06-10 10:27
@ScopeyNZ hits it on the head. This module is designed to provide a restful interface to the application data. In most circumstances, that API interface would not be accessed by a user who's happened to log in via the web interface or has an active web session. This service is intended for server-to-server communication.

If you have a specific use-case where you want that to happen, then you need to add your own authentication layer to do so (which is simple enough).
